- hosts: all
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: fail2ban, tags: ['fail2ban'] }
    - { role: ufw, tags: ['ufw'] }
    - { role: fstab, tags: ['fstab'] }
