---

- name: install fail2ban
  apt:
    state: latest
    package:
      - fail2ban

- name: set up fail2ban
  command: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
           creates=/etc/fail2ban/jail.local
  notify: restart fail2ban
